// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpsqtkztzjduzjgacwrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwc3F0a3p0empkdXpqZ2Fjd3JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTc1MzcsImV4cCI6MjA2NzU5MzUzN30.3vuWqsgWFRA80Io-NBIzsZMDs1YWbOff-PCGRoQ9PEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});